FROM python:3.11-bookworm

RUN apt update && apt install -y --no-install-recommends pandoc git

WORKDIR /app

COPY requirements.cpu.txt .
RUN python3 -m pip install --no-cache-dir --no-deps -r requirements.cpu.txt

COPY context_chat_backend context_chat_backend
COPY context_chat_backend/persistent_storage/config.cpu.yaml context_chat_backend/persistent_storage/config.yaml
COPY main.py .

ENTRYPOINT ["python3", "main.py"]
